### ISSUE TITLE
balenaEtcher and privacy/GDPR

### ISSUE THREAD

**Issue by roan** [raspberrypi/documentation#1266]
According to https://github.com/balena-io/etcher/issues/2497 there are some concerns about privacy and GDPR compliance. As balenaEtcher is the suggested program for creating the sd card, could this be a problem?

**Comment by JamesH65** [comment]
Thanks for the heads up, I'm passing it on to our legal team.

**Comment by lurch** [comment]
https://github.com/balena-io/etcher/issues/2599#issuecomment-504042827 says the Etcher team are looking into it too.

**Comment by rradar** [comment]
This is **well known to** the **balena** team since **minimum august 2017** (https://github.com/balena-io/etcher/issues/2497#issuecomment-508932329)

They (balena) don't take any actions since eve - no matter how many heads ups (@JamesH65). :whale2:

Guess we just need to wait for the Greece Authority (Hellenic Data Protection Authority (HDPA)) to take action and wake up some people here. Last company they fined 5 weeks ago was a 150k€ :boxing_glove:...

**Comment by JamesH65** [comment]
This is not the place to discuss it - we are not balena. Since no actual GDPR lawyers have commented, on any threads I have read, to say it's a definite infringement, for the moment we will assume it isn't.  If balena want to take the risk, that is down to them, but we won't be playing internet lawyers here.

**Comment by pinchies** [comment]
@JamesH65 People are upset about the privacy infringement, not just the GDPR infringement.

**Comment by JamesH65** [comment]
Not sure what you point is, on a 6 month old closed thread. 

But, we have just released our own Imaging Software and changed out documentation to recommend that , so you don't really need to use Etcher if you don't want to.
