### ISSUE TITLE
login appears on incorrect screen 

### ISSUE THREAD

**Issue by Fannattatic** [raspberrypi/documentation#1316]
When Raspbian is booted with login desktop enabled the login prompt appears on HDMI-1 but in my case this isn't the primary screen, since HDMI-2 is the primary screen it should appear on HDMI-2.
I have included some attachments to show the displays and the screen configuration:

![image](https://user-images.githubusercontent.com/50067585/67619693-56b18200-f7f6-11e9-82f6-2d982051cab9.png)
![image](https://user-images.githubusercontent.com/50067585/67619700-721c8d00-f7f6-11e9-8984-3476b8d56554.png)
![image](https://user-images.githubusercontent.com/50067585/67619704-82346c80-f7f6-11e9-869c-bcaee893126d.png)

HDMI-1 resolution is 2560x1080 plugged into HDMI0
HDMI-2 resolution is 1680x1050 plugged into HDMI1

I don't think this will affect anything though

Also adding a button to make a specific display the default display would be very nice because currently the display to the left will be the default display.

**Comment by JamesH65** [comment]
This is the wrong repo for this report, its should be in the raspbian desktop repo - this one is for documentation only.

@spl237 Which is the correct repo?

**Comment by spl237** [comment]
The login prompt is always displayed on what X views as the primary monitor, which is HDMI-1 in a dual HDMI setup. Rearranging the displays, as you have done, does not affect which monitor X regards as primary.

It is possible to change the primary monitor by adjusting X settings, but because the only thing this actually affects is the location of the login prompt - it doesn't affect the taskbar, desktop, windows or anything else - the option to change it is not offered to the user, as it caused too much confusion as to what it actually did. If you want to change it yourself, you will need to manually reconfigure the xrandr settings in /usr/share/dispsetup.sh

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved. (And shouldn't really be in this repo anyway)
