### ISSUE TITLE
vcgencmd get_mem arm result less on raspberry pi 4 with 4GB RAM

### ISSUE THREAD

**Issue by gwh-cpnet** [raspberrypi/documentation#1325]
![Screenshot_2019-11-05_14-00-20](https://user-images.githubusercontent.com/29444942/68182580-b36e2300-ffd4-11e9-9ea4-8a3ce090c6a7.png)

according to the [doc](https://github.com/raspberrypi/documentation/blob/JamesH65-patch-vcgencmd-vcdbg-docs/raspbian/applications/vcgencmd.md#get_mem), the sum of memories for the arm and gpu is supposed to be 4GB, right?

I have a stats script that runs on various types of raspberry pi. I hope I can get the memory specification right on all of them.

**Comment by JamesH65** [comment]
This is expected behaviour (albeit rather counterintuitive). The firmware, which is what vcgencmd is interrogating, only sees the first 1G of RAM, so this call will return 1G - the gpu memory allocated.

To determine ARM memory size available to Linux, you should use Linux command, e.g. https://www.cyberciti.biz/faq/how-to-check-memory-debian-linux/

**Comment by gwh-cpnet** [comment]
@JamesH65  Thank you for the explaination.
