### ISSUE TITLE
全新购买的树莓派4b刷入最新版系统raspberry后wifi能搜索到但是输入密码无反应

### ISSUE THREAD

**Issue by 15230745073** [raspberrypi/documentation#1495]
全新购买的树莓派4b刷入最新版系统raspberry后wifi能搜索到但是输入密码无反应
wpa工具也无效

**Comment by lurch** [comment]
Google translates that to:
"After the newly purchased Raspberry Pi 4b is flashed into the latest version of the system raspberry, wifi can be searched but the password is not responded
wpa tool is also invalid"

That's a question for the [forums](https://www.raspberrypi.org/forums/) rather than this documentation repo.

**Comment by JamesH65** [comment]
Unfortunately, we can only deal with English language reports on here. Having used Google translate however, it seems you need to use the forums for help. This repo is for reporting problems with  the documentation.  www.raspberrypi.org/forums

**Comment by 15230745073** [comment]
Thanks, I will go to the forum for help
