### ISSUE TITLE
SFTP doesn't allow writing of files and folders

### ISSUE THREAD

**Issue by xihay34616** [raspberrypi/documentation#1708]
https://www.raspberrypi.org/documentation/remote-access/ssh/sftp.md

You tell people, the only thing they have to do is start Filezilla, connect to the RPi and everything runs as expected. No further help, no helpful links.

As it is, my RPi 3 was freshly installed last month, it is up to date and I can connect to it via SFTP. But I can't write to it. Not with the only user I know on it: pi

I tried to find something with Google, Startpage, Duckduckgo. Maybe my English is much too bad, but I can't find anything. I'm no programmer (it's not funny you have to create a programmer's account just to contact anyone that the documentation is missing important parts!). And I don't have a clue about SFTP. Last year you had to follow a tutorial for about 2h to get FTP working on a PI. With right management and everything else, described precisely.
Now you find nothing.

If security is the most important thing of life, even more important than the air we breathe, please make a complete documentation. You know, I don't close any packaging these days  that I can't open alone...

**Comment by JamesH65** [comment]
I just followed the Filezilla instructions for Linux and it worked first time. Was able to copy a file directly to the Pi. What OS are you using, WIndows? What SFTP application?

Since you say it does connect, so you can see the files, there's something else going on somewhere.  Probably best to ask for technical support on the forums (www.raspberrypi.org/forums) where technical help can be provided.

BTW, github isn't just for programmers, its used for a wide variety of thing - like the documentation you see here.

**Comment by lurch** [comment]
>  Last year you had to follow a tutorial for about 2h to get FTP working on a PI. ... Now you find nothing.

Looks to me like FTP and SFTP _are_ both still mentioned on https://www.raspberrypi.org/documentation/remote-access/ :shrug:

**Comment by JamesH65** [comment]
Closing as no fault found. Please use our forums for technical support.
