### ISSUE TITLE
Schematics "USB Power In" shows incorrect CC1 and CC2 pulldown

### ISSUE THREAD

**Issue by RowanP4069** [raspberrypi/documentation#1915]
The [schematics](https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/rpi_SCH_4b_4p0_reduced.pdf)  (accessed 2021-06-17) have not been updated for the [new ](https://hackaday.com/2020/02/23/raspberry-pi-slips-out-new-pcb-version-with-usb-c-power-fix/) _USB-C Power In_ circuit. They still show CC1 and CC2 shorted and pulled down by a single 5K1 resistor (R79).

**Comment by lurch** [comment]
ping @jimbojr / @mike-stimson

**Comment by aallan** [comment]
Schematics will be moved outside of the documentation repo during the reorganisation, see #1911. We may look at this then.

**Comment by seamusdemora** [comment]
After reading #1911, I don't understand... The schematics aren't a *3rd party product* AFAICT - are they? Also - open-sourcing the schematic would presumably resolve the workload issue, and be a significant aid to the user community.

**Comment by JamesH65** [comment]
The current schematics will be available  in the new docs world, just in a different place. Updating them is a different issue and may or may not happen.

**Comment by seamusdemora** [comment]
Right... when I said "I don't understand", I meant that I don't see the point of having schematics if they're not going to be kept up to date.

**Comment by aallan** [comment]
> I meant that I don't see the point of having schematics if they're not going to be kept up to date.

We have a very limited amount of engineering time. It's on a list, but the list is very long, and it's not near the top. I'll be looking at this issue, alongside other similar issues to do with ongoing maintenance of the documentation, as part of #1911.

**Comment by seamusdemora** [comment]
> We have a very limited amount of engineering time. It's on a list, but the list is very long

Yes, I understand that there may be a resource issue, and prioritization is necessary. But you didn't remark on the *open-sourcing* alternative. It's obvious that there **is** an up-to-date schematic somewhere, and it's obvious that it must be maintained. Two questions arise here: 

   1. Would it not be more *resource-efficient* to make the up-to-date/complete schematic available - rather than spending additional resources to create and update a **partial** schematic? 
   2.  Is there a **policy** within the Foundation that prohibits open-sourcing a complete & up-to-date schematic? 

From my own experience, and many comments I've read over the past couple of years, my *sense* is that the limited schematic is not very useful. It would follow that an incorrect/out-of-date schematic would be even less useful. 

And so - given all the above, it would seem that a more *forthcoming* statement would be a preferable closure to this issue.

**Comment by JamesH65** [comment]
Raspberry Pi's are not open source hardware, and we are unlikely to change that stance.

**Comment by hachi** [comment]
Can we bump this open again please... the docs site update happened some months ago and this wasn't addressed and now we have no external tracking for when this gets done.

**Comment by JamesH65** [comment]
There is no schedule for this, nor is there any guarantee it will actually be done.

**Comment by OliverZuckerberg** [comment]
Sad.

**Comment by ryao** [comment]
> Raspberry Pi's are not open source hardware, and we are unlikely to change that stance.

Then what is this:

https://datasheets.raspberrypi.com/rpi4/raspberry-pi-4-reduced-schematics.pdf

They published a schematic. They should update it to reflect the state of the production hardware. This can be useful to people developing hardware based on the CM4.

**Comment by TamtamHero** [comment]
>    Raspberry Pi's are not open source hardware, and we are unlikely to change that stance.

Pretty disappointed by this answer. It's absurd to publish the v1 schematics but not update them later. What are you guys afraid of ?

I'm currently learning about electronics and USB-C. I was about to make the same mistake you did, connecting CC1 and CC2 together, but I've been lucky enough to come across the RPI 4 case.  "Great!" I thought. "I'm gonna look at their fixed schematics to see how they fixed that!"
And then I discover that it's not fixed yet after many years, for dumb pretexts.
I've been advocating for Raspberry boards since the first one, but I see that I've been misled. Sad.

**Comment by aallan** [comment]
As I said up thread. We have a small engineering and documentation team. It's on a list of things that need doing, but the list is very long, and it's not anywhere near the top. Calling us names isn't going to help your case.

**Comment by seamusdemora** [comment]
@aallan said, "Calling us names isn't going to help your case."

Nor does it seem it's going to hurt the case either. :)
