### ISSUE TITLE
ToC non-functional with Javascript disabled

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#2013]
In #1935 @Gadgetoid complains that the new site is "a little bit completely broken without Javascript" which I was kinda surprised by.
So I gave it a try myself with JS turned off, and it seems that https://www.raspberrypi.org/documentation/ works okay (with the exception of the search box, because that's entirely implemented by javascript), https://www.raspberrypi.org/documentation/accessories/ works okay, and the _contents_ of e.g. https://www.raspberrypi.org/documentation/accessories/display.html works okay.
AFAICT it seems that the only bit that doesn't work is the exapanding and collapsing of sections in the Table of Contents on the left? _Perhaps_ we should tweak things so that **if** JS is disabled, the ToC is fully-expanded rather than being fully-collapsed?

**Comment by aallan** [comment]
Thoughts @nelliemckesson ?

**Comment by Gadgetoid** [comment]
FWIW the page I landed on was this - https://www.raspberrypi.org/documentation/computers/configuration.html

And the left-hand navigation looked "complete" ish (I wasn't aware of the drop down menu at this point) but clicking the links did nothing so it felt like I'd been dropped on a looooonnng page with now way to navigate it. Yes... I'm the kind of difficult pedant who browses the web with javascript disabled by default.

As @lurch suggests, I'd recommend a "progressive enhancement" approach whereupon the submenus are always enabled - ie: not hidden by default with the CSS - and only hidden by javascript at runtime. This *usually* happens fast enough that you don't get a surprising flash of expanded menus.

style.css line ~207 shows these submenu items require a "hidden" class in order to be hidden, so just removing that from the HTML and adding it at runtime with JS would suffice:

```css
nav#contents .itemcontents.hidden,
nav#mobile-contents .contents-inner.hidden {
  height: 0px;
  overflow: hidden;
}
```

(Granted the main thrust of web development experience is at least 5 years out of date so I could be spouting nonsense.)

**Comment by lurch** [comment]
ping @Gadgetoid The fix for this is now live at https://www.raspberrypi.org/documentation/ :slightly_smiling_face:
