### ISSUE TITLE
Bug in Table-of-Contents Rendering

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2056]
If you go to https://www.raspberrypi.org/documentation/microcontrollers/rp2040.html. Then click on MicroPython in the ToC it expands to this,

<img width="362" alt="Screenshot 2021-08-12 at 13 55 45" src="https://user-images.githubusercontent.com/53625/129200511-38136b0d-ff7a-40c3-bfc2-8e53854bfa63.png">

However, there is a missing section in that list. If you go there directly from the category page, or by clicking on "What is MicroPython?" you'll see this,

<img width="341" alt="Screenshot 2021-08-12 at 13 55 50" src="https://user-images.githubusercontent.com/53625/129200640-d02a8921-abb4-4b47-ab27-420a63d54b4f.png">

which correctly lists the two sections which should appear in the ToC. Don't know if this is a toolchain bug, or a CSS bug, so ping both @lurch and @nelliemckesson.

**Comment by lurch** [comment]
https://raw.githubusercontent.com/raspberrypi/documentation/develop/documentation/asciidoc/microcontrollers/micropython/what-is-micropython.adoc uses `== What is MicroPython?`

https://raw.githubusercontent.com/raspberrypi/documentation/develop/documentation/asciidoc/microcontrollers/micropython/drag-and-drop.adoc uses `## Drag-and-Drop MicroPython`

Do you want me to update the build system to cope with both `##` as well as `==`?

BTW the reason there's different behaviour from different pages, is because when you're on the RP2040 page and then expand the "MicroPython" section in the ToC, the ToC you're seeing there (for the non-current page) is the one generated by our build system.
But when you're on the MicroPython page itself, the ToC (for the current-page only) is instead generated (dynamically) by [Tocify](http://gregfranko.com/jquery.tocify.js/) based on the headers on the page.

(Here starts a long and rather detailed aside...)
This is also why the anchor links in the LH ToC are _occasionally_ different depending on whether you're viewing a ToC anchor-link on the current-page, or on a non-current page that you've manually expanded the ToC for.
For example, if you're looking at https://www.raspberrypi.org/documentation/computers/os.html and manually expand the "Configuration" page and then scroll the ToC down to the "Device Trees, Overlays, and Parameters" section, then the "Device Tree Overlays" subsection has the anchor-link https://www.raspberrypi.org/documentation/computers/configuration.html#part2 . This is because https://raw.githubusercontent.com/raspberrypi/documentation/develop/documentation/asciidoc/computers/configuration/device-tree.adoc says:
```
[[part2]]
=== Device Tree Overlays
```

But if you go to https://www.raspberrypi.org/documentation/computers/configuration.html itself and then scroll down to the same section in the ToC, the "Device Tree Overlays" subsection has the anchor-link https://www.raspberrypi.org/documentation/computers/configuration.html#device-tree-overlays (because Tocify builds the anchor-links just from the headers themselves). Whilst this anchor-link "works" on this page (i.e. clicking on the item in the ToC scrolls the content-part of the page to the correct place), unfortunately this Tocify-generated anchor-link doesn't work correctly from "external pages", i.e. if you click on https://www.raspberrypi.org/documentation/computers/configuration.html#device-tree-overlays in this GitHub issue, it does take you to https://www.raspberrypi.org/documentation/computers/configuration.html but it leaves you sitting at the top of the page rather than scrolling down to the "Device Tree Overlays" part of the page. (Whereas clicking on https://www.raspberrypi.org/documentation/computers/configuration.html#part2 does auto-scroll you to the correct part of the page)

**Most** of the time this isn't a problem, because the build-system-generated anchor-link is the _same_ as the Tocify-generated anchor-link. E.g if you repeat the above experimentation with the "HDMI Groups and Mode" subsection on the Configuration page, then both the build-system and Tocify generate the identical https://www.raspberrypi.org/documentation/computers/configuration.html#hdmi-groups-and-mode anchor-link (thanks to the custom hasher function I added to Tocify [here](https://github.com/raspberrypi/documentation/blob/develop/jekyll-assets/_includes/scripts.html#L10) ), so in this case the anchor-link created by Tocify **does** work from external pages.

I believe this "Tocify-created anchor-links sometimes don't work from external pages" is only a minor issue, and it'll probably become even _less_ of an issue once #1991 has been fixed (which will be using the AsciiDoctor-generated anchors, and I spent a fair chunk of time ensuring that the build-system-generated anchors are the same as the AsciiDoctor-generated anchors).

**Comment by aallan** [comment]
> Do you want me to update the build system to cope with both ## as well as ==?

🤦‍♂️ 

No. That's totally on me. I was having a weird Asciidoc vs Markdown moment today. I caught myself a couple of times writing Markdown, I'll fix this tomorrow.

**Comment by aallan** [comment]
> In that case I guess it's worth adding in a warning (to the build-system) if erroneous Markdown-headers are detected?

Yeah, that's definitely worth it. I hate that Asciidoc accepts Markdown headers. This isn't the first time I've accidentally started writing Markdown. 😐
