### ISSUE TITLE
cmdline.txt sytax (dwc_otg.lpm_enable)

### ISSUE THREAD

**Issue by dshaw619** [raspberrypi/documentation#2083]
The documentation re. Command Line Options (https://www.raspberrypi.org/documentation/computers/configuration.html#command-line-options) says "dwc_otg.lpm_enable: turns off Link Power Management ...".  It seemed incredibly counter-intuitive that an option called "enable" would turn something off until I noticed that the actual syntax in one of my cmdline.txt files was "dwc_otg.lpm_enable=0".  It would seem appropriate to define the acceptable values for this option (and others?) in the documentation.

**Comment by andrum99** [comment]
I've filed #2085 which corrects the documentation so the setting reads `dwc_otg.lpm_enable=0`, i.e. with `=0` on the end. This is enough to correct the page so it correctly documents the default setting. I don't think it is necessary to document any other setting of this parameter, since it is the default setting and should always be set on the Raspberry Pi. You may wish to check this with the relevant engineer though.
