### ISSUE TITLE
NVMe documentation is out of date

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/documentation#2352]
documentation/computers/raspberry-pi.html#nvme-ssd-boot

It says you need pre-release software but the bullseye release and latest stable bootloader has everything you need.
I had a request to publish a list of drives that we know work. This might be a big dodgy but I'll push an update for someone to review.

**Comment by lurch** [comment]
In previous years we've had similar requests for lists of known-working SD cards and known-working USB drives, but I believe we've always refrained from doing so, because:
* any such list will always be hopelessly incomplete
* what works for one person may not work for another person, e.g. if they're using a marginal power supply
* what used to "not work" might work in future, with updated bootloader / firmware / kernel
* with cheap SD cards there's also the problem of counterfeits

:shrug:

**Comment by lurch** [comment]
> It says you need pre-release software but the bullseye release and latest stable bootloader has everything you need.

Does it also work out-of-the-box with (the stable bootloader and) Buster Legacy?

**Comment by peterharperuk** [comment]
> Does it also work out-of-the-box with (the stable bootloader and) Buster Legacy?

Yes, and new devices should have the required bootloader installed already.

**Comment by aallan** [comment]
> I had a request to publish a list of drives that we know work.

While we need to update the documentation to say "this works now" I agree with @lurch, I don't think we want to publish a list. It'll be continually out of date, and always incomplete.

**Comment by aallan** [comment]
Thanks @peterharperuk !
