### ISSUE TITLE
Duplicate assigned section

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#2359]
Building on `develop` we get the following error, 

```
asciidoctor: WARNING: build/adoc_includes/computers/config_txt/conditional.adoc: line 2: id assigned to section already in use: conditional-filters
```

which I don't remember always getting? Is this something to do with #2351 perhaps @lurch?

**Comment by lurch** [comment]
I had a look at that (when I saw the warning myself) and AFAICT it seems to be because in https://raw.githubusercontent.com/raspberrypi/documentation/develop/documentation/asciidoc/computers/config_txt/conditional.adoc
```
[[conditional-filters]]
== Conditional Filters
```
The explicit-ID is the same as the ID generated from the title (on line 2), and this confuses asciidoctor and causes it to emit a harmless warning? So we _could_ remove the `[[conditional-filters]]` part to get rid of the warning, but my instinct would be to leave it in there in case we ever decide to rename the header? :shrug: :shrug:

**Comment by aallan** [comment]
I'm tempted to rename the header just to make the warning go away 🤣 

But, yup. Makes sense.
