### ISSUE TITLE
RPi 4 soft temp limit

### ISSUE THREAD

**Issue by pbevilac** [raspberrypi/documentation#2546]
[https://www.raspberrypi.com/documentation/computers/raspberry-pi.html](url) states:
_The Raspberry Pi 4 Model B, continues with the same PCB technology as the Raspberry Pi 3 Model B+, to help dissipate excess heat. There is currently no soft limit defined._

I did some thermal testing with my new RPi 4, default configuration, and I can trigger the related info bits, 3 and 19, which happened at about 82'C, note no other bit is set.

```
pi@raspi-1GB:/boot  $ vcgencmd get_throttled
throttled=0x80008
pi@raspi-1GB:/boot $ vcgencmd version
Mar 24 2022 13:19:26
Copyright (c) 2012 Broadcom
version e5a963efa66a1974127860b42e913d2374139ff5 (clean) (release) (start)
pi@raspi-1GB:/boot $ cat /proc/cpuinfo
...
Hardware        : BCM2711
Revision        : a03115
Serial          : 10000000a4711dc7
Model           : Raspberry Pi 4 Model B Rev 1.5

```
So, it seems to me that the doc snippet is incorrect.

**Comment by andrum99** [comment]
The 'soft limit' wording is from the Pi 3B+ days. If the Pi 4's SoC goes above a set temperature then the firmware will reduce the clock - this is the same process as the 'hard limit' for the Pi 3B+. I don't know why it was decided to call one 'hard' and the other 'soft', as they both perform a similar function. In the case of the Pi 3B+, I believe the soft limit reduces the ARM frequency by less, whereas the hard limit takes it all the way down to the minimum. For Pi 4B, the backoff on frequency is progressive. The throttled bits are designed to give an indication of whether the SoC has been throttled since boot, and whether the SoC is currently throttled and are working as designed for the Pi 4. Unlike previous models, Pi 4 never sets the warranty bit.
