### ISSUE TITLE
[TUTORIAL] Avoid the expression "static IP" when you really mean "fixed IP"

### ISSUE THREAD

**Issue by epoch1970** [raspberrypi/documentation#2715]
E.g. https://www.raspberrypi.com/tutorials/running-pi-hole-on-a-raspberry-pi/

**Comment by aallan** [comment]
You're drawing the distinction here that a "fixed" IP is an instruction (or rather a request) to your router to assign the same IP address next time the DHCP lease expires, versus a "static" IP which is (usually) set by the client? 

If so, while technically correct, the two terms are used more or less interchangeably in the literature, and the term "static" is used far more widely. I'm not sure about this one really. I think the distinction will be lost on most people.

**Comment by lurch** [comment]
`static inline void* ip_address;` ? :laughing:

**Comment by epoch1970** [comment]
The distinction is between global (dynamic) and local (static) configuration. A network is a distributed system.
Global config works and local config is bound to make the network fail.

Why would users configure a "static IP" in their router if they can configure a "static IP" on their own computer?

**Comment by aallan** [comment]
> Why would users configure a "static IP" in their router if they can configure a "static IP" on their own computer?

Because the tutorial tells them to?

**Comment by epoch1970** [comment]
I'll have to disagree. There is a conceptual difference between the two configuration methods. The superiority of one over the other should be clear to anyone once that difference is clearly spelt out.
If contrasting the two methods in a couple of sentences is too difficult, at least I would avoid using the same exact term to reference them.
I'd prefer readers develop an appetite for learning, rather than following.

**Comment by lurch** [comment]
With the complexity of networking, I suspect there are many different overlapping terms, probably used interchangeably by different people. For example, "Global config" to me would imply something on the internet-side of my router, and "local config" would imply something on the LAN-side of my router :shrug: 

> Why would users configure a "static IP" in their router if they can configure a "static IP" on their own computer?

Personally, I like to do that because it means my Pi gets the same IP address regardless of what OS I've flashed to it, and I don't have to mess about with networking settings on the SD card (to get a static IP) each time I flash a new OS.

Of course if you know what you're doing (which you obviously do), you're able to adapt the tutorial's instructions to suit your preferred setup. But in that case you're probably not the (primary) intended audience for the tutorial?
