### ISSUE TITLE
Older devices will roll back to X Windows

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3057]
Raspberry Pi boards before Pi 4 will run X Windows on Bookworm, rather than Wayland. Only Raspberry Pi 4 and CM4 and Pi 400 will run Wayland. Needs to be made clear in relevant places.

**Comment by lurch** [comment]
This has already been partly touched upon in https://github.com/raspberrypi/documentation/blob/bookworm/documentation/asciidoc/computers/configuration/display-rotation.adoc

**Comment by jehlers42** [comment]
Assuming this is still relevant?
https://github.com/raspberrypi/documentation/blob/f29454812b3ba3067c5cb54b73f496522c2f1586/documentation/asciidoc/computers/camera/libcamera_apps_getting_started.adoc?plain=1#L5

Ditto this?
https://github.com/raspberrypi/documentation/blob/f29454812b3ba3067c5cb54b73f496522c2f1586/documentation/asciidoc/computers/camera/libcamera_options_common.adoc?plain=1#L92

Otherwise I've got feelers out for answers surrounding references in the following articles:
- https://github.com/raspberrypi/documentation/blob/bookworm/documentation/asciidoc/accessories/display/troubleshooting.adoc
- https://github.com/raspberrypi/documentation/blob/bookworm/documentation/asciidoc/computers/remote-access/secure-shell-from-unix.adoc
- https://github.com/raspberrypi/documentation/blob/bookworm/documentation/asciidoc/computers/remote-access/vnc.adoc

**Comment by jehlers42** [comment]
Sounds like the following decisions so far:
- Still relevant, update to define Bullseye as Legacy OS
- Needs a specialist answer
- Some implementations have right-click built in to the config, @spl237 will test ours next week
- Answer TBD
- Looks like there's a config file the user can create for wayvnc that may perform the same actions re: authentication. Would need to be tested but would be a good addition if it works in a similar fashion.

**Comment by lurch** [comment]
I asked @naushir and @davidplowman about that libcamera and Glamor stuff a while ago, and they told me they weren't sure what the answer was, it still needed testing.

**Comment by lurch** [comment]
> Some implementations have right-click built in to the config, @spl237 will test ours next week

I just checked with Simon, and he says there's currently no way to emulate a right-click on the touchscreen in Wayland (he says it _might_ be added in a future version).

**Comment by aallan** [comment]
> > Some implementations have right-click built in to the config, @spl237 will test ours next week
> 
> I just checked with Simon, and he says there's currently no way to emulate a right-click on the touchscreen in Wayland (he says it _might_ be added in a future version).

Okay big `[WARNING]` box on the [Touch Screen](https://www.raspberrypi.com/documentation/accessories/display.html) page to this effect then. Lets get this and #3086 closed out as soon as possible.

**Comment by lurch** [comment]
Replying to the points and replies that @jehlers42 raised earlier (thanks Josh!)

>> Assuming this is still relevant?
>> https://github.com/raspberrypi/documentation/blob/f29454812b3ba3067c5cb54b73f496522c2f1586/documentation/asciidoc/computers/camera/libcamera_apps_getting_started.adoc?plain=1#L5
> * Still relevant, update to define Bullseye as Legacy OS

Josh has done this.

>> Ditto this?
>> https://github.com/raspberrypi/documentation/blob/f29454812b3ba3067c5cb54b73f496522c2f1586/documentation/asciidoc/computers/camera/libcamera_options_common.adoc?plain=1#L92
> * Needs a specialist answer

I changed "X Windows" to "desktop".

>> * https://github.com/raspberrypi/documentation/blob/bookworm/documentation/asciidoc/accessories/display/troubleshooting.adoc
> * Some implementations have right-click built in to the config, @spl237 will test ours next week

Already mentioned above, and docs have been updated.

>> * https://github.com/raspberrypi/documentation/blob/bookworm/documentation/asciidoc/computers/remote-access/secure-shell-from-unix.adoc
> * Answer TBD

I checked yesterday, and `ssh -Y` still works with X-forwarding (i.e. run a program on your Pi, and have its window displayed on your Linux laptop), even if you're running Wayland on the Pi. So no changes needed.

>> * https://github.com/raspberrypi/documentation/blob/bookworm/documentation/asciidoc/computers/remote-access/vnc.adoc
> * Looks like there's a config file the user can create for wayvnc that may perform the same actions re: authentication. Would need to be tested but would be a good addition if it works in a similar fashion.

This probably counts as part of #2904 

----
So this issue is back down to just the original "Needs to be made clear in relevant places." which I'll now be working on...

**Comment by lurch** [comment]
> "Needs to be made clear in relevant places."

I _think_ this is just the "raspi-config advanced options" section and the "setting HDMI resolution" section (which I've now both updated), so I'm going to close this.
@aallan @tobybroberts @jehlers42 @nathan-contino feel free to re-open if you spot any other areas of the documentation where it'd be useful to explain that some Pis run Wayland but some Pis will run X11.
