### ISSUE TITLE
Site doesn't build with Doyxgen 1.9.8

### ISSUE THREAD

**Issue by aallan** [raspberrypi/documentation#3288]
Need to investigate why the site doesn't build with Doxygen 1.9.8.

**Comment by aallan** [comment]
Linking #3283 which is the branch we'll be using to look at this one!

**Comment by nelliemckesson** [comment]
I'm pretty sure it's because of the file names doxygen is using for 1.9.8 -- the toolchain relies on a file called modules.html which lists all the files in the build. It looks like this file has been renamed files.html. I need to see if files.html exactly matches the former modules.html and if we can get the site to build by just adding that file name as an option, or if more is required.
