### ISSUE TITLE
pi5: peripheral address missing, and bcm_host_get_peripheral_address() broken

### ISSUE THREAD

**Issue by cleverca22** [raspberrypi/documentation#3350]
https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#peripheral-addresses
this page makes no mention of the peripheral base addr on the pi5

`bcm_host_get_peripheral_address()` also claims the peripherals start at just `10`

```c
#include <stdint.h>
#include <sys/mman.h>
#include <stdio.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <bcm_host.h>

int main(int argc, char **argv) {
  uint64_t physaddr;
  physaddr = bcm_host_get_peripheral_address();
  printf("addr %lx\n", physaddr);
  return 0;
}
```
this code returns `addr 10`

**Comment by aallan** [comment]
On Pi 5 GPIO is controlled via [the RP1](https://www.raspberrypi.com/documentation/microcontrollers/rp1.html). See the RP1 Peripherals document, https://datasheets.raspberrypi.com/rp1/rp1-peripherals.pdf.

**Comment by cleverca22** [comment]
@aallan i know most gpio is controlled by the RP1, and in this use-case, i didnt want an RP1 register
i was after the old ST_CLO register in the VPU timer, which i did find after some brute-forcing

but that does raise an interesting problem
with how the pi5 has re-arranged all of the SoC registers, and moved most stuff the user wants to the RP1, the old `bcm_host_get_peripheral_address()` is kind of useless
any offsets you would have done from there are now going to be wrong, no matter which base it returns

**Comment by aallan** [comment]
@pelwell thoughts here?

**Comment by pelwell** [comment]
The source code for the bcm_host library lived in the userland repo, the README for which states:

> This repo is ancient and deprecated.
> 
> It largely contains code using proprietary APIs to interface to the VideoCore firmware. We have since move to standard linux APIs.
> 
> V4L2, DRM/KMS and Mesa are the APIs you should be using.
> 
> The few useful tools from here (dtoverlay, dtmerge, vcmailbox, vcgencmd) have been moved to the raspberrypi/utils repo.
> 
> Code from here is no longer installed on latest RPiOS Bookworm images.
> 
> If you are using code from here you should rethink your solution.
> 
> Consider this repo closed.

There is no correct return value for `bcm_host_get_peripheral_address()` on Pi 5 other than NULL, but updating it would imply that the library still has a life.

**Comment by aallan** [comment]
@pelwell At that point I'm presuming this section https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#peripheral-addresses needs rewriting?

**Comment by pelwell** [comment]
I think we should just delete it. What do you think, @popcornmix ?

**Comment by popcornmix** [comment]
I agree. The repo the code is from has been closed, and I don't think the code is useful enough to resurrect it
(especially as most uses are unlikely to be applicable to Pi5 which uses RP1 for many equivalent peripherals).

**Comment by aallan** [comment]
Okay, I'll yank that entire section.

**Comment by aallan** [comment]
Removed entire section in ddfba6d. Will go to the live site next time I push to production.

**Comment by Seneral** [comment]
This is quite concerning if I understand this right.
bcm_host, including direct peripheral access, is still very necessary for some niche use cases, and so the documentation is still relevant.
For example, it's the only way I am aware of to access the QPU directly (especially in a headless use case without kernel graphics drivers), as documented originally by [Herman Hermitage](https://github.com/hermanhermitage/videocoreiv/wiki/VideoCore-IV-Programmers-Manual), and actively used by me in [VC4CV](https://github.com/Seneral/VC4CV) and my project [AsterTrack](https://github.com/AsterTrack/AsterTrack).
The mailbox interface is frankly not powerful enough to replace this, and I do not know of any other kernel driver exposing the required level of control to the userspace.

**Comment by lurch** [comment]
Hello @Seneral , I've discussed this with some of the other engineers, and they tell me:
* bcm_host was removed because large parts of it no longer make sense in a Pi 5 world
* For getting raw peripheral addresses, you should be reading the values from DeviceTree (although we'd always advise you to access peripherals via their standard Linux APIs where possible, rather than directly banging the registers, as this isolates you from future hardware changes)
* Direct QPU access is no longer possible on Pi 5 (access isn't implemented in the Pi 5 EEPROM), and deprecated on Pi 4 and earlier (because the OpenGL driver is now implemented on the ARM side rather than in the firmware)
* It is still possible to submit QPU jobs from the ARM side through an ioctl - see https://github.com/raspberrypi/linux/issues/6660 for some example code

**Comment by Seneral** [comment]
Thanks for your detailed response!
I've since come to the same conclusion and replaced bcm_host with direct access to the DeviceTree.
I'm only targeting the VC4 right now anyway as I'm writing the assembly code by hand, but looking at the issue you linked, that looks about as powerful as what I'm using right now, minus the debug registers that proved quite valuable diagnosing misbehaving programs. Still, seems like a better way forward.
