### ISSUE TITLE
Cant access the files in usb after burn pixel raspi iso

### ISSUE THREAD

**Issue by princeofgambit** [raspberrypi/documentation#512]
1. I have burn the pixel iso on 128 usb drive that contain around 60gb data.As per my understanding at that time,etcher will burn on empty space (guess warning should be issued here at website) and the data in usb will not be affected.
2.After I burn the iso, I can boot the pixel os and play around.But when I reboot,I cant access the 60gb data via Window explorer.It asked me to format the disk.
3.Checking the usb partition,I discover 2 diff partitions,but still have no idea how to recover my 60gb data
4.I try to reformat the pixel 1.2gb part to fat and use undelete software like recuva etc but not successful
5.try to set the 114gb part to active but not succesful also

Pls help as i really need my 60gb data back

**Comment by XECDesign** [comment]
1) Etcher will overwrite all the data at the start of the disk.
2) That's expected
3) In general, you can't. You may be able to recover bits and pieces using various data recovery tools. If there's anything that's very important, you should stop using the disk immediately and take it to a data recovery specialist.
4 & 5) I wouldn't expect anything like that to work. Anything you write to the disk only makes it more difficult to recover data. Don't format it, don't write to it, don't do anything until you know what you're doing.

I would recommend posting this question of the forum, since this isn't a documentation-related issue.
