### ISSUE TITLE
3.3V regulator + TSOP38 = 55.55 Hz noise

### ISSUE THREAD

**Issue by arthurmoises** [raspberrypi/documentation#656]
Didn't found the best place to post this issue, as I have not found a hardware repository. 

When attempting to connect the 3.3V rail (or any 3.3V pin as HIGH) to the Vin of the TSOP38 (metal case), the output pin shows a 55.55Hz noise, every time, messing with the IR signal readings. 

I have tested the same circuit on a Wemos D1 Mini, which didn't output those noises. My thought is that there is happening an interference with Raspberry Pi 3 Model B (the only that I've tested so far) 3.3V Voltage Regulator. 

The solution that I came to my project was to use a voltage divider (100Ohm/100Ohm+100Ohm) to the 5V rail, and that worked, which confirms that the interference is originated in the 3.3V regulator + TSOP38 combination. 

The 5V rail directly to the TSOP38 did not output any background noise. The 3.3V rail directly to the Logic Analyzer didn't output any noise too. So it's a combination of both the 3.3V regulator and the TSOP. 

For newbies that don't have a solid knowledge of electronics, the solution of the voltage divider works good, since the supply current of TSOP is only 3mA.

**Comment by lurch** [comment]
I'm very much an electronics newbie myself, but I wonder if a decoupling/smoothing capacitor would help?

**Comment by arthurmoises** [comment]
Hi lurch! I've tried to to that too, before attempting to use the voltage divider resistors. I've used a 4.7uF film capacitor (those blue cubic ones) and a 680 Ohm resistor (which have output 608 Ohm on multimeter), to try to create a high-pass filter at the frequency of 55.55Hz. Even with those, I've managed to get some interference sometimes. 

I guess that I've could managed a better filter design, but as I was with lack of components at the time, I tough: "Why instead of trying to filter the noise, I haven't he noise at first?" So I discovered that the 5V rail didn't have the noise, and them, attempted to lower that to the voltage of 3.3V, which worked! For production board, I'll try to use an IC level shifter, instead of the voltage dividers.

**Comment by JamesH65** [comment]
This is too off topic for the docs repo, so closing. I'd suggest using the forums for this sort of discussion.

**Comment by HFATL** [comment]
I've noticed also that my Raspberry Pi 3 is spewing much noise into my SDR radio which I listen remotely. As expected, any SDR on HF frequencies is very noise sensitive. Connected directed to a laptop the SDR radio gives much less noise.

In your experience the 3.3v regulator is the only culprit? I guess all I have to do is bypass the regulator and use a voltage dividir from 5V to 3.3V, correct?


Many thanks,

João Fonseca

**Comment by JamesH65** [comment]
As I said above, this is NOT the place to discuss this, please use the forums, it will get a much larger audience.

**Comment by N1MKG** [comment]
-------- Original message --------From: HFATL <notifications@github.com> Date: 5/3/18  15:54  (GMT-05:00) To: raspberrypi/documentation <documentation@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [raspberrypi/documentation] 3.3V regulator + TSOP38 = 55.55 Hz
  noise (#656) 
I've noticed also that my Raspberry Pi 3 is spewing much noise into my SDR radio which I listen remotely. As expected, any SDR on HF frequencies is very noise sensitive. Connected directed to a laptop the SDR radio gives much less noise.
In your experience the 3.3v regulator is the only culprit? I guess all I have to do is bypass the regulator and use a voltage dividir from 5V to 3.3V, correct?
Many thanks,
João Fonseca

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/raspberrypi/documentation","title":"raspberrypi/documentation","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/raspberrypi/documentation"}},"updates":{"snippets":[{"icon":"PERSON","message":"@HFATL in #656: I've noticed also that my Raspberry Pi 3 is spewing much noise into my SDR radio which I listen remotely. As expected, any SDR on HF frequencies is very noise sensitive. Connected directed to a laptop the SDR radio gives much less noise.\r\n\r\nIn your experience the 3.3v regulator is the only culprit? I guess all I have to do is bypass the regulator and use a voltage dividir from 5V to 3.3V, correct?\r\n\r\n\r\nMany thanks,\r\n\r\nJoão Fonseca "}],"action":{"name":"View Issue","url":"https://github.com/raspberrypi/documentation/issues/656#issuecomment-386416489"}}}
