### ISSUE TITLE
Selecting audio output used by omxplayer

### ISSUE THREAD

**Issue by lurch** [raspberrypi/documentation#68]
According to `usage/audio/README.md`, omxplayer should output audio over whatever default audio device you've configured in `raspi-config`.
However it seems that when video is being displayed over HDMI, omxplayer ignores the value set by raspi-config, and to get audio playing over the headphone port I actually have to do 'omxplayer -o local la.mp3`.

Can somebody more familiar with omxplayer confirm this is indeed the expected behaviour? If so, I'll have a go at updating the `usage/audio/README.md` page.

**Comment by chadi8** [comment]
Hello !
@popcornmix 
i'm using omxplayer wrapper,
is there any command that i can make omxplayer always use aux? 
other then omxplayer -o file.mp3

Thank you !

**Comment by JamesH65** [comment]
This issue was closed in 2014 and your question is much better asked on the forums.

**Comment by obskyr** [comment]
@popcornmix I have HDMI connected (and no 3.5mm plug connected), and running `tvservice -d edid.dat && edidparser edit.dat` reports `HDMI:EDID has HDMI support and audio support`. Despite this, no audio is routed to HDMI unless I use `-o hdmi` (which I'd rather not have to). What could this be due to? Is there a bug in omxplayer's HDMI detection, or is it something else?

**Comment by lurch** [comment]
@obskyr That sounds like a question for https://github.com/popcornmix/omxplayer/issues rather than this documentation repo.

**Comment by obskyr** [comment]
Oh, whoops, it sure is. I thought I was there!
