### ISSUE TITLE
Add a section on the OTP bit values

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/documentation#886]
See https://github.com/raspberrypi/firmware/issues/974 for details.

**Comment by JamesH65** [comment]
See https://github.com/raspberrypi/documentation/blob/JamesH65-otpbits/hardware/raspberrypi/otpbits.md for a WIP

**Comment by lurch** [comment]
I wonder if "All member of the Raspberry Pi range have a onboard One Time Programmable (OTP) memory block." would be better phrased something like "All SoCs used by the Raspberry Pi range have an inbuilt One Time Programmable (OTP) memory block." ?

To me, "onboard" makes it sound like it's just another chip on the PCB, rather than something that's part of the SoC itself, IYSWIM.

**Comment by JamesH65** [comment]
Makes sense, I'll make some changes.

**Comment by JamesH65** [comment]
This is now merged

https://www.raspberrypi.org/documentation/hardware/raspberrypi/otpbits.md
