### ISSUE TITLE
RPi Zero W OTG Schematic

### ISSUE THREAD

**Issue by jebentancour** [raspberrypi/documentation#902]
I can´t find the schematics of this part. I want to know if it its possible to use USB OTG and power the Raspberry Pi from the GPIO header.

**Comment by lurch** [comment]
AFAIK all the 5V rails on the Pi Zero W are simply connected together; which means if you want to use it in USB OTG mode (i.e. having the PiZero appearing as a USB device instead of a USB host) then you either need to prevent the Pi also being powered via the GPIO header _or_ you need to snip the 5V wire in the USB OTG cable.

**Comment by JamesH65** [comment]
The schematics are not released, so probably best to ask this sort of question on the forum, although @lurch has probably [provided the information needed.

**Comment by jebentancour** [comment]
Thanks @lurch !
