### ISSUE TITLE
Linux manual SD card installation instructions: Checking successful writes on large SD cards

### ISSUE THREAD

**Issue by tillyboy** [raspberrypi/documentation#914]
https://github.com/raspberrypi/documentation/blob/master/installation/installing-images/linux.md

The last paragraph (Checking whether the image was correctly written to the SD card) suggests to `dd` from the SD card to the local drive. In cases where the SD card is significantly larger than the image (I noticed this on a 64GB card), this takes forever and writes a ton of unneeded data to the hard drive.

I suggest you complement those instructions by suggesting to always run `dd` with `status=progress` and to kill the command once a certain threshold has been reached (e.g. 4GB, which is more than twice the size of the light image, I don't know for the full raspbian image though), to avoid 60+ mins of potentially filling your harddrive with a bunch of 0s.

I stopped after 10 GB, truncated and `diff -s` confirmed for me that both files are identical.

**Comment by JamesH65** [comment]
What we could do, since the DD command to write the image displays the number of blocks written, we could limit the read back DD to that number of blocks. e.g.

dd if=test.bin of=test2.bin bs=4K
100+0 records in    <<<<< this is the number of blocks written
100+0 records out
409600 bytes (410 kB, 400 KiB) copied, 0.00144744 s, 283 MB/s

So we could then limit the read back

dd bs=4M if=/dev/sdX of=from-sd-card.img count=xxx where xxx is the count from the write.

**Comment by lurch** [comment]
...except @JamesH65 has used `bs=4K` in the dd-write, but `bs=4M` in the dd-read. Typo? :wink:

**Comment by JamesH65** [comment]
Sort of, I did the tests using a smaller file, with smaller block sizes. Needs adjusting for the actual command used.

**Comment by JamesH65** [comment]
Please see #946 for a go at fixing this.
